### ISSUE TITLE
K8S 환경에서 Google Cloud Build와 Helm을 통한 빌드&배포

### ISSUE THREAD

**Issue by GangHun-Jo** [QPI-kr/admin-server#31]
## Google Cloud Build
로컬에서 이미지를 로컬 빌드하는 건 비용이 크므로 Cloud Build를 사용해서 이미지를 빌드한다.
나중에 Web Hook을 통해서 특정 브랜치에 커밋되면 자동으로 빌드되게 구현할 수도 있음.
트리거 생성 -> 깃허브 연동 -> Yaml 작성
```
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        docker pull gcr.io/$PROJECT_ID/qpi-admin:latest || exit 0
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >
        docker build -t gcr.io/$PROJECT_ID/qpi-admin:latest --cache-from
        gcr.io/$PROJECT_ID/qpi-admin:latest .
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        docker push gcr.io/$PROJECT_ID/qpi-admin:latest
    id: publish
    entrypoint: bash
timeout: 1800s
```
각 스텝
1. 직전 이미지 pull(cache를 위함)
2. 새로 build with cache
3. 저장소에 push
